#!/bin/python3
##############################################################################
##
##       Copyright (C) 2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       pyproject.toml
##
## Purpose-
##       PIP517 build hooks
##
## Last change date-
##       2023/08/12
##
##############################################################################
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "stdio"
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
dynamic = ["authors", "description", "version"]

[tool.setuptools.packages]
find = {}
