##############################################################################
##
##       Copyright (C) 2026 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/license/mit)
##
## SPDX-License-Identifier: MIT
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization
##
## Last change date-
##       2026/02/25
##
##############################################################################

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKEXE)
endif

.PHONY: default
default: $(DEFAULT)

##############################################################################
## Add library controls and dependencies
include $(INCDIR)/pub/Makefile.BSD

##############################################################################
## Makefile cleanup
clean : clean.dir
.PHONY: clean.dir
clean.dir: ;
	@rm -f trace.*
