##############################################################################
##
##       Copyright (c) 2007-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile versioning
##
## Last change date-
##       2024/02/10
##
##############################################################################

##############################################################################
## Local module list
################################### Optional targets
MAKEXE := $(patsubst $(OBJDIR)/Test_lex,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/Test_Sys,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/Test_win,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/Testparm,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/TestUnit,,$(MAKEXE))

################################### Objects
MAKEXE := $(patsubst $(OBJDIR)/Test_SMS,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/SMS_base,,$(MAKEXE))
MAKEXE := $(patsubst $(OBJDIR)/SMS_Pool,,$(MAKEXE))

################################### Controls
CINCL  += -I$(OBJDIR)############## Local include directory

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

default: $(DEFAULT)

.PHONY: make.dir
make.dir: Enviro

.PHONY: make.all
make.all: $(MAKEXE)
make.all: Base_SMS Pool_SMS

all: make.all

##############################################################################
## TARGET: Base_SMS
Base_SMS: Test_SMS.o SMS_base.o
	$(CC) -o $@ $^ $(CLOAD) $(LLIBS) $(CLIBS)

##############################################################################
## TARGET: Pool_SMS
Pool_SMS: Test_SMS.o SMS_Pool.o
	$(CC) -o $@ $^ $(CLOAD) $(LLIBS) $(CLIBS)

##############################################################################
## Dependencies
include $(INCDIR)/com/Makefile.BSD

##############################################################################
## Makefile cleanup
clean : clean.dir
.PHONY: clean.dir
clean.dir: ;
	-@rm -f debug.out Logger.log    >/dev/null 2>/dev/null
	-@rm -f debug.log MediaTest.out >/dev/null 2>/dev/null
	-@rm -f Base_SMS  Pool_SMS      >/dev/null 2>/dev/null
