##############################################################################
##
##       Copyright (C) 2010 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
## SPDX-License-Identifier: MIT
##############################################################################
## Makefile.BSD
##############################################################################

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKOBJ)
endif

.PHONY: default
default: $(DEFAULT)

