##############################################################################
##
##       Copyright (c) 2007-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile versioning
##
## Last change date-
##       2025/01/27
##
##############################################################################

##############################################################################
## Local module list
MAKEXE :=
MAKEXE += rdserver
MAKEXE += rdclient
MAKEXE += FSlist

MAKLIB := RdCommon.o RdPatch.o CommonThread.o

##############################################################################
## Set default target
.PHONY: default
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKEXE)
endif

default: $(DEFAULT)

##############################################################################
## Controls
include $(INCDIR)/com/Makefile.BSD
include $(INCDIR)/pub/Makefile.BSD

##############################################################################
## TARGET: install
.PHONY: install
install: rdclient rdserver
	strip $^
	cp -idp $^ ~/bin

##############################################################################
## TARGET: RdClient
rdclient: RdClient.o $(MAKLIB) ClientThread.o
	$(CC) -o $@ $^ $(CLIBS)

##############################################################################
## TARGET: RdServer
rdserver: RdServer.o $(MAKLIB) ListenThread.o ServerThread.o
	$(CC) -o $@ $^ $(CLIBS)
