##############################################################################
##
##       Copyright (c) 2007-2026 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/license/mit)
##
## SPDX-License-Identifier: MIT
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile versioning
##
## Last change date-
##       2026/07/05
##
##############################################################################

##############################################################################
## Local module list
MAKEXE :=
MAKEXE += rdclient
MAKEXE += rdserver

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKEXE)
endif

default: $(DEFAULT)

##############################################################################
## Controls
include $(INCDIR)/pub/Makefile.BSD

##############################################################################
## TARGET: rdclient, rdserver
rdclient: RdClient.o IoCommon.o RdCommon.o CommonThread.o ClientThread.o
	$(CC) -o $@ $^ $(CLIBS)

rdserver: RdServer.o IoCommon.o RdCommon.o CommonThread.o ListenThread.o ServerThread.o
	$(CC) -o $@ $^ $(CLIBS)

##############################################################################
## TARGET: install
install: rdclient rdserver
	strip rdclient rdserver
	cp -idp rdclient ~/bin/rdclient
	cp -idp rdserver ~/bin/rdserver
