##############################################################################
##
##       Copyright (c) 2018-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization
##
## Last change date-
##       2024/11/12
##
## Implementation notes-
##       export USE_STATIC=true to build static library (for use with gdb)
##
##############################################################################
MAKEXE := ######################### Default, no executables
MAKEXE += recompile.brian
MAKEXE += Brian
MAKOBJ := $(patsubst $(OBJDIR)/Brian.o,,$(MAKOBJ))
MAKEXE += HttpClient
MAKOBJ := $(patsubst $(OBJDIR)/HttpClient.o,,$(MAKOBJ))

##############################################################################
## Optional executables, built on demand
## Dirty:   Used for debugging, not distributed
## Include: Used for include file testing (distributed)
OPTEXE += Dirty ##################### Dirty, if provided, only built on demand
MAKOBJ := $(patsubst $(OBJDIR)/Dirty.o,,$(MAKOBJ))
OPTEXE += Dirty-demo################## Dirty, if provided, only built on demand
MAKOBJ := $(patsubst $(OBJDIR)/Dirty-demo.o,,$(MAKOBJ))
OPTEXE += Include #################### Include is only built on demand
MAKOBJ := $(patsubst $(OBJDIR)/Include.o,,$(MAKOBJ))

##############################################################################
## Local options
COPTS  += -fPIC ###################### Generate position independent code

MODULE := Brian
CYGDLL :=
CYGDLL += -shared -o cyg${MODULE}.dll
CYGDLL += -Wl,--out-implib=cyg${MODULE}.dll.a
CYGDLL += -Wl,--export-all-symbols
CYGDLL += -Wl,--enable-auto-import

ifneq "" "$(LINKMAP)"
CYGDLL += -Wl,-Map -Wl,cyg${MODULE}.map ## Generate linker map
endif

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKEXE)
endif

.PHONY: default
default: $(DEFAULT)

##############################################################################
## TARGET: cygBrian.dll libBrian.dll libBrian.so libBrian.a
cyg${MODULE}.dll: $(MAKOBJ)
	$(CC) $(CYGDLL) $^ $(CLIBS) $(CYGMAP)
	rebase -b 0x2F0000000 $@
	touch $@

lib${MODULE}.so.1.0: $(MAKOBJ)
	$(CC) -shared -o $@ $^ $(CLIBS) $(LIBMAP)

lib${MODULE}.so: lib${MODULE}.so.1.0
	ln -sf $< $@

lib${MODULE}.dll: lib${MODULE}.so.1.0
	ln -sf $< $@

lib${MODULE}.a: $(MAKOBJ)
	$(AR) $@ $(MAKOBJ)

##############################################################################
## TARGET: $(MAKEXE)
LLIBS  += -L. -lBrian

ifeq "" "$(USE_STATIC)"
  USE_SHARED:= true
  ifeq "CYGWIN" "$(findstring CYGWIN,$(shell uname))"
    $(MAKEXE) $(OPTEXE): cyg${MODULE}.dll D/cygpub.dll
  else
    $(MAKEXE) $(OPTEXE): lib${MODULE}.so D/libpub.so
  endif
else
  $(MAKEXE) $(OPTEXE): lib${MODULE}.a L/libpub.a
endif

include $(INCDIR)/pub/Makefile.BSD

CLIBS  += -L$(SHRDIR) -lpub
CLIBS  += $(shell pkg-config --libs libcurl)

## Always recompile Brian
PHONY: recompile.brian
recompile.brian: ;
	rm -f Brian.o

##############################################################################
## Run the default program
.PHONY: do
do: Brian
	@Brian

##############################################################################
## Test
.PHONY: echo
echo: ;
	@echo CLIBS  '$(CLIBS)'
	@echo LLIBS  '$(LLIBS)'
	@echo LIBDIR '$(LIBDIR)'
	@echo MAKEXE '$(MAKEXE)'
	@echo MAKOBJ '$(MAKOBJ)'
	@echo MODULE '$(MODULE)'
	@echo OPTEXE '$(OPTEXE)'
	@echo USE_SHARED '$(USE_SHARED)'
	@echo USE_STATIC '$(USE_STATIC)'

##############################################################################
## Makefile cleanup
clean: clean.dir
.PHONY: clean.dir
clean.dir: ;
	@rm -f cyg${MODULE}.dll cyg${MODULE}.dll.a
	@rm -f lib${MODULE}.dll lib${MODULE}.so*
	@rm -f lib${MODULE}.a
	@rm -f typescript Dirty* trace* ##### (Testing files)
