#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2022-2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       regression
##
## Purpose-
##       Run regression tests.
##
## Last change date-
##       2023/01/14
##
##############################################################################

##############################################################################
## Insure that the library is up to date
pushd ../. >/dev/null
echo ""
pwd
make
rc=$?
popd >/dev/null
[[ $rc != 0 ]] && { echo "Library build failed"; exit 1; }

##############################################################################
## Insure that test executables are up to date
echo ""
pwd
make
[[ $? != 0 ]] && { echo "Test build failed"; exit 1; }

##############################################################################
## Run the tests
echo ""
echo "T_Stream --server --client --verbose **********************************"
T_Stream --server --client --verbose
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo T_Stream --server --stress --verbose "**********************************"
T_Stream --server --stress --verbose
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo "T_Stream --server --stress=1 --verbose ********************************"
T_Stream --server --stress=1 --verbose
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo "T_Stream --server --stress=10 --verbose *******************************"
T_Stream --server --stress=10 --verbose
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo "T_Option **************************************************************"
T_Option
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo "T_Quick --verbose *****************************************************"
T_Quick --verbose
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }

echo ""
echo "TestIoda **************************************************************"
TestIoda
[[ $? != 0 ]] && { echo "Test failed"; exit 1; }
