##############################################################################
##
##       Copyright (C) 2020-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization
##
## Last change date-
##       2025/05/04
##
##############################################################################

##############################################################################
## Set default paths
BINDIR = ../../../bin################# Binary directory


##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= $(MAKEXE)
endif

.PHONY: default
default: $(DEFAULT)

##############################################################################
## Add library controls and dependencies
include $(INCDIR)/com/Makefile.BSD
include $(INCDIR)/pub/Makefile.BSD

##############################################################################
## Target: install
.PHONY: install install-fileman install-filedate install-scanner

install: install-fileman install-filedate install-scanner
install-fileman: $(BINDIR)/fileman
install-filedate: $(BINDIR)/fileman.date
install-scanner: $(BINDIR)/scanner

$(BINDIR)/fileman: Fileman
	strip $<
	cp -fp $< $@

$(BINDIR)/fileman.date: $(SRCDIR)/fileman.date
	cp -fp $< $@

$(BINDIR)/scanner: Scanner
	strip $<
	cp -fp $< $@

##############################################################################
## Cleanup
.PHONY: MAK_clean
clean:  MAK_clean
MAK_clean: ;
	@rm -f debug.*
