##############################################################################
##
##       Copyright (c) 2023-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       ~/src/cpp/lib/dev/Makefile.DIR
##
## Purpose-
##       Subdirectory build control: included from ~/src/cpp/lib/Makefile.BSD
##
## Last change date-
##       2024/02/10
##
##############################################################################

##############################################################################
## Source/object files
DEV_SOURCE :=
DEV_SOURCE += $(wildcard $(INCDIR)/dev/*)
DEV_SOURCE += $(wildcard $(SRCDIR)/dev/*)

DEV_OBJECT := $(patsubst dev/%.cpp,dev/%.o,$(wildcard dev/*.cpp))

##############################################################################
## Dependency controls
DEV_DEPEND := dev/.have-version dev/Makeproj.gcc ## Dependency requirements

dev/.have-version: $(LIB_SOURCE) ##### If dev/.have-version out of date
	(cd $(OBJDIR)/dev/; $(MAKE) config)## Update it. (Full recompile possible)
	touch $@

dev/Makeproj.out: $(DEV_SOURCE) ###### If any source changed, make required
	touch $@

dev/Makeproj.gcc: dev/Makeproj.out ### If compilation might be needed
	(cd $(OBJDIR)/dev/; $(MAKE) depend; $(MAKE) all) ## Remake, updating depend
	echo -n "Last compile (check): " >$@; date >>$@  ## Avoid secondary remake

$(DEV_DEPEND): $(OBJDIR)/libpub.a $(OBJDIR)/libpub.so

##############################################################################
## TARGETS: dev/libdev.a libdev.a
$(OBJDIR)/dev/libdev.a: $(DEV_DEPEND)

$(OBJDIR)/libdev.a: $(OBJDIR)/dev/libdev.a
	$(shell [ ! -L "$@" ] && ln -s $< $@)
	touch $@

lib: $(OBJDIR)/libdev.a
## usr: $(USRLIB)/libdev.a             ## [Currently not in $(USRLIB)]

##############################################################################
## TARGETS: dev/libdev.so.1.0 libdev.so
$(OBJDIR)/dev/libdev.so.1.0: $(DEV_DEPEND)

$(OBJDIR)/libdev.so.1.0: $(OBJDIR)/dev/libdev.so.1.0
	$(shell [ ! -L "$@" ] && ln -s $< $@)
	touch $@

.SECONDARY: $(USRLIB)/libdev.so.1.0
shr: $(OBJDIR)/libdev.so
usr: $(USRLIB)/libdev.so

##############################################################################
## TARGETS: dev/libdev.dll libdev.dll
$(OBJDIR)/dev/libdev.dll: $(OBJDIR)/dev/libdev.so.1.0
	(cd $(OBJDIR)/dev/; $(MAKE) shr)
	touch $@

$(OBJDIR)/libdev.dll: $(OBJDIR)/dev/libdev.dll
	$(shell [ ! -L "$@" ] && ln -s $< $@)
	touch $@

dll.shr: $(OBJDIR)/libdev.dll
dll.usr: $(USRLIB)/libdev.dll

##############################################################################
## TARGET: dev.depend
.PHONY: dev.depend
depend: dev.depend
dev.depend: ;
	(cd $(OBJDIR)/dev/; $(MAKE) depend)

##############################################################################
## TARGET: dev.update
.PHONY: dev.update
update: dev.update
dev.update: ;
	(cd $(OBJDIR)/dev/; $(MAKE) update)

##############################################################################
## Cleanup
.PHONY: dev.pristine
pristine: dev.pristine
dev.pristine: ;
	(cd $(OBJDIR)/dev/; $(MAKE) pristine)
	@rm -f $(USRLIB)/libdev.*

.PHONY: dev.clean
clean: dev.clean
dev.clean: ;
	@rm -f libdev.*
