##############################################################################
##
##       Copyright (c) 2023-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       ~/src/cpp/lib/dev/Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization.
##
## Last change date-
##       2024/03/21
##
##############################################################################

##############################################################################
## Local options
COPTS  += -fPIC ###################### Generate position independent code
module := dev
CYGDLL :=
CYGDLL += -shared -o cyg${module}.dll
CYGDLL += -Wl,--out-implib=lib${module}.dll.a
CYGDLL += -Wl,--export-all-symbols
CYGDLL += -Wl,--enable-auto-import
ignore += -Wl,--whole-archive ${old_libs}
ignore += -Wl,--no-whole-archive ${dependency_libs}

ifneq "" "$(LINKMAP)"
CYGDLL += -Wl,-Map -Wl,lib${module}.map
endif

##############################################################################
## Set targets
ifeq "" "$(DEFAULT)"
DEFAULT := all
endif

.PHONY: default all lib shr update
default: $(DEFAULT)
all: lib shr
lib: .have-version
shr: .have-version
lib: libdev.a
update: all

ifneq "" "$(findstring CYGWIN,$(shell uname))"
shr: cygdev.dll
else
shr: libdev.so.1.0
endif

##############################################################################
## TARGET: libdev.a
libdev.a: $(MAKOBJ)
	rm -f $@
	$(AR) $@ $^
	touch $@

##############################################################################
## TARGETS: cygdev.dll libdev.so.1.0
cygdev.dll: $(MAKOBJ)
	$(CC) $(CYGDLL) $^ -LD -lpub $(CLIBS)
	rebase -b 0x250000000 $@
	touch $@

libdev.so.1.0: $(MAKOBJ)
	$(CC) $(LINKMAP) -shared -o $@ $^ -LD -lpub $(CLIBS)
	touch $@

##############################################################################
## TARGET: config
.PHONY: config
config: ;
	@../../../../bat/sys/configure.sh src/cpp/lib/dev

.have-version: ../../../../bat/sys/.want-version
	$(MAKE) config
	touch $@

##############################################################################
## Dependencies
include $(INCDIR)/dev/Makefile.BSD

##############################################################################
## Cleanup
.PHONY: dev.clean dev.pristine
clean: dev.clean
dev.clean: ;
	@rm -f cygdev.* libdev.*
	@rm -f Makeproj.*

pristine: dev.pristine
dev.pristine: ;
	@rm -f .have-version
