##############################################################################
##
##       Copyright (c) 2023-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       ~/src/cpp/lib/dev/Makefile.DIR
##
## Purpose-
##       Subdirectory build control: included from ~/src/cpp/lib/Makefile.BSD
##
## Last change date-
##       2024/04/21
##
##############################################################################

##############################################################################
## Source/object files
DEV_SOURCE :=
DEV_SOURCE += $(wildcard $(INCDIR)/dev/*)
DEV_SOURCE += $(wildcard $(SRCDIR)/dev/*)

DEV_OBJECT := $(patsubst dev/%.cpp,dev/%.o,$(wildcard dev/*.cpp))

##############################################################################
## Dependency controls
DEV_DEPEND := dev/.have-version dev/Makeproj.all ## Dependency requirements

dev/.have-version: $(LIB_SOURCE) ##### If dev/.have-version out of date
	(cd $(OBJDIR)/dev/; $(MAKE) config)## Update it. (Full recompile possible)
	touch $@

dev/Makeproj.all: $(DEV_SOURCE) ###### Recompile/rebuild
	(cd $(OBJDIR)/dev/; $(MAKE) depend; $(MAKE) all) ## Remake, updating depend
	touch $@

dev/Makeproj.all: dev/.have-version pub/Makeproj.all

##############################################################################
## TARGETS: static/libdev.a
$(STATIC)/libdev.a: dev/libdev.a
	cp -Lpf $< $@
	touch $@

lib: $(STATIC)/libdev.a
dev/libdev.a: dev/Makeproj.all
	touch $@

dev/Makeproj.all: $(STATIC)/libpub.a

##############################################################################
## TARGETS: shared/cygdev.dll shared/libdev.so.1.0 shared/libdev.so
$(SHARED)/cygdev.dll: dev/cygdev.dll
	cp -Lpf $< $@
	touch $@

.SECONDARY: $(SHARED)/libdev.so.1.0
$(SHARED)/libdev.so.1.0: dev/libdev.so.1.0
	cp -Lpf $< $@
	touch $@

$(SHARED)/libdev.so: $(SHARED)/libdev.so.1.0
	$(shell [ ! -L "$@" ] && (cd $(SHARED); ln -s $(<F) $(@F)))
	touch $@

ifeq "CYGWIN" "$(findstring CYGWIN,$(shell uname))"
shr: $(SHARED)/cygdev.dll
dev/Makeproj.all: $(SHARED)/cygpub.dll
dev/cygdev.dll: dev/Makeproj.all
else
shr: $(SHARED)/libdev.so
dev/Makeproj.all: $(SHARED)/libpub.so
dev/libdev.so.1.0: dev/Makeproj.all
endif

##############################################################################
## TARGET: dev.depend
.PHONY: dev.depend
depend: dev.depend
dev.depend: ;
	(cd $(OBJDIR)/dev/; $(MAKE) depend)

##############################################################################
## TARGET: dev.update
.PHONY: dev.update
update: dev.update
dev.update: ;
	(cd $(OBJDIR)/dev/; $(MAKE) update)

##############################################################################
## Cleanup
.PHONY: dev.pristine
pristine: dev.pristine
dev.pristine: ;
	(cd $(OBJDIR)/dev/; $(MAKE) pristine)
	@rm -f $(SHARED)/cygdev.* $(SHARED)/libdev.*
	@rm -f $(STATIC)/libdev.*

.PHONY: dev.clean
clean: dev.clean
dev.clean: ;
	@rm -f dev/cygdev.* dev/libdev.* dev/Makeproj.*
