##############################################################################
##
##       Copyright (c) 2023-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       ~/src/cpp/lib/dev/Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization.
##
## Last change date-
##       2024/02/01
##
##############################################################################

##############################################################################
## Local options (-fPIC, but not on CYGWIN)
ifneq "CYGWIN" "$(findstring CYGWIN,$(shell uname))"
COPTS  += -fPIC ###################### Generate position independent code
endif

##############################################################################
## Set targets
ifeq "" "$(MAKRUN)"
MAKRUN := all
endif

ifeq "" "$(DEFAULT)"
DEFAULT := $(MAKRUN)
endif

.PHONY: default all dll lib
default: configure $(DEFAULT)
all: dll lib
dll: libdev.so.1.0
lib: libdev.a

##############################################################################
## TARGET: libdev.a
libdev.a: $(MAKOBJ)
	$(AR) $@ $^
	touch $@

##############################################################################
## TARGET: libdev.so.1.0
libdev.so.1.0: $(MAKOBJ)
	$(CC) -shared -o $@ $^ -lbz2 -lz -lc
ifeq "CYGWIN" "$(findstring CYGWIN,$(shell uname))"
	rebase -b 0x250000000 $@
endif
	touch $@

##############################################################################
## TARGET: configure
.PHONY: configure
configure: ;
	@../../../../bat/sys/configure.sh src/cpp/lib/dev

##############################################################################
## TARGET: update
.PHONY: update
update: default

##############################################################################
## Dependencies
include $(INCDIR)/dev/Makefile.BSD

ifneq "" "$(DEPENDS)"
Makeproj.dep: $(wildcard $(INCDIR)/dev/*)
Makeproj.dep: $(wildcard $(SRCDIR)/*)
Makeproj.dep: $(wildcard $(SRCDIR)/dev/OS/USR/*) ## (non-existent)
Makeproj.dep: $(wildcard $(SRCDIR)/dev/OS/BSD/*) ## (non-existent)
endif

##############################################################################
## Cleanup
.PHONY: dev.clean dev.pristine
clean: dev.clean
dev.clean: ;
	-@rm -f libdev.a >/dev/null 2>/dev/null
	-@rm -f libdev.so* libdev.dll >/dev/null 2>/dev/null

pristine: dev.pristine
dev.pristine: ;
	-@rm -f _have.version >/dev/null 2>/dev/null
