#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2020 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       bluebird
##
## Purpose-
##       Create -cs root/linux rexterm terminals
##
## Last change date-
##       2020/04/10
##
## Usage-
##       bluebird
##
## Implementation note-
##       See: ~/bat/.tweaks --bluebird
##
##############################################################################

##############################################################################
## Optional clock window
if [[ "$1" = "-clock" ]] ; then
  xclock -geometry -0+0 &
fi

##############################################################################
## Create the xterm windows
source .tweaks --bluebird
rexterm -cs root  -geometry $bluebird_root
rexterm -cs linux -geometry $bluebird_user

