#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       bluebird
##
## Purpose-
##       Create -cs root/linux rexterm terminals
##
## Last change date-
##       2019/10/07
##
## Usage-
##       bluebird
##
##############################################################################

##############################################################################
## Optional clock window
if [[ "$1" = "-clock" ]] ; then
  xclock -geometry -0+0 &
fi

##############################################################################
## Create the xterm windows
rexterm -cs root  -geometry 80x24-0+164
rexterm -cs linux -geometry 80x24-164+0

