#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       boogers
##
## Purpose-
##       Look for files which crop up now and then.
##
## Last change date-
##       2019/10/07
##
## Usage-
##       boogers {AUX}
##
##############################################################################

##############################################################################
## Look for booger files
cd $1
ftool core "*smit*" "*.stackdump"

