#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       delink
##
## Purpose-
##       Remove links (and only links) from specified list
##
## Last change date-
##       2019/10/08
##
## Usage-
##       delink filename ...
##
##############################################################################
ls -adlN $* | \
awk '/^l/ {print $9}' | \
xargs -i rm {}

