#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       detar
##
## Purpose-
##       Extract a tar file.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       detar filename
##
##############################################################################
tar -xvf $1.tar

