#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       detar
##
## Purpose-
##       Extract a gzipped tar file.
##
## Last change date-
##       2023/06/06
##
## Usage-
##       detar {-v} filename
##
##############################################################################

##############################################################################
## Extract switch names
sparm=""

for i in $*
do
  case $i in
    -c)
      echo "Invalid switch $i"
      heading $0
      exit 1
      ;;

    -f)
      echo "Specify the input filename as the only positional parameter"
      heading $0
      exit 1
      ;;

    -*)
      sparm="$sparm $i"
      shift
      ;;

    *)
      break
      ;;

  esac
done

##############################################################################
## Extract parameters
if [ "" = "$1" ] ; then
  echo "Missing input tar_file(.tgz) name"
  heading $0
  exit
fi
tar_name=$1
shift

if [ "" != "$1" ] ; then
  echo "Too many parameters"
  heading $0
  exit
fi

##############################################################################
## Verify parameters
if [ ! -f "$tar_name.tgz" ] ; then
  echo "'$tar_name.tgz' not found."
  exit
fi

if [ -e "$tar_name" ] ; then
  echo "'$tar_name' already exists. It's the output directory name."
  echo "Delete it and try again."
  exit
fi

##############################################################################
## Extract the tgz file
cmd="tar $sparm -xzf $tar_name.tgz"
echo $cmd
$cmd
rc=$?
[[ $rc != 0 ]] && echo "tar command failed, exit code $rc"
exit $rc

