#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2020 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       dir
##
## Purpose-
##       List directory entry (overrides /usr/bin/dir when aliases missing)
##
## Last change date-
##       2020/01/19
##
## Usage-
##       dir filename ...
##
##############################################################################
ls -alF "$@"

