#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       dirtail
##
## Purpose-
##       List (tail of) directory content.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       dirtail fileList
##
##############################################################################
if [ -z "$TAILSIZE" ] ; then
  TAILSIZE=10
fi

ls -rt -alF $* | tail -$TAILSIZE

