#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2021 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       e
##
## Purpose-
##       Edit files.
##
## Last change date-
##       2021/05/06
##
## Usage-
##       e filename ...
##
##############################################################################
[ -z "$EDITOR" ] && export EDITOR="$HOME/bin/edit"
if [[ ! -x "$EDITOR" ]] ; then
  editor=`whence $EDITOR`
  if [[ ! -x "$editor" ]] ; then
    echo "$0 ERROR: can't execute EDITOR: $EDITOR"
    exit
  fi
  EDITOR="$editor"
fi

$EDITOR "$@"
## clear

