#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2021 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       e
##
## Purpose-
##       Edit files.
##
## Last change date-
##       2021/01/23
##
## Usage-
##       e filename ...
##
##############################################################################
pgm=$HOME/bin/edit
if [[ ! -x "$pgm" ]] ; then
  echo "$0 ERROR: can't execute $pgm"
  exit
fi

$pgm "$@"
## clear

