#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2026 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/license/mit)
##
## SPDX-License-Identifier: MIT
##----------------------------------------------------------------------------
##
## Title-
##       editgpg
##
## Purpose-
##       Edit a GPG encrypted file.
##
## Last change date-
##       2026/04/30
##
## Usage-
##       editgpg filename
##
## Implementation notes-
##       GPG configuration information is kept in ~/.gnupg/.
##       Using information in filename.gpg, GPG automatically selects the
##       decryption key.
##
##       There is no default encryption key.
##       - Use the default configuration file, ~/.gnupg/gpg.conf to define the
##         default encryption key.
##       - This default encryption key *MUST* be in the secret key list.
##       IF YOU ENCODE WITH AN ENCRYPTION KEY YOU CANNOT DECODE, YOUR DATA
##       WILL BE IRRETRIEVABLY LOST.
##
##       "gpg --list-keys" displays your key ring.
##       "gpg --list-secret-keys" displays your secret key ring.
##
## See also:
##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
##
##############################################################################

##############################################################################
## Function: USAGE
function usage
{
  echo ""
  echo "$0: Edit a file encrypted by GPG."
  echo "Usage: $0 filename"
  echo "File \"filename.gpg\" must exist; \"filename\" should not."
  echo "The GPG encrypted file is decrypted into \"filename\", "
  echo "then this unencrypted file is edited."
  echo "If \"filename\" still exists when the editor exits, the file is"
  echo "the file is reencrypted and replaces \"filename.gpg\" "

  echo ""
  echo "The information in \"filename.gpg\" allows GPG to automatically"
  echo "select the decryption key."

  echo ""
  echo "GPG configuration information is kept in ~/.gnupg/gpg.conf"
  echo "There is no default encryption key."
  echo "- Use the default configuration file, ~/.gnupg/gpg.conf to define the"
  echo "  default encryption key."
  echo " -This default encryption key *MUST* be in your secret key list."

  echo ""
  echo "  ** WARNING**"
  echo "    IF YOU CANNOT DECODE THE ENCRYPTION KEY, YOUR DATA WILL BE LOST."
  echo "    IT'S IRRETRIEVABLY LOST; THE ORIGINAL FILE IS *DELETED*"
}

##############################################################################
## Parameter check
if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
  usage
  exit 1
fi

GPGFILE=$1
if [[ -z "$GPGFILE" ]] ; then
  echo "ERROR: Filename not specified"
  usage
  exit 1
fi

if [[ ! -z "$2" ]] ; then
  shift
  echo "ERROR: Extra parameters: $@"
  usage
  exit 1
fi

if [[ ! -f "$GPGFILE.gpg" ]] ; then
  echo "ERROR: File \"$GPGFILE.gpg\" does not exist"
  if [[ -f "$GPGFILE" ]] ; then
    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
  fi
  usage
  exit 1
fi

if [[ -f "$GPGFILE.gpg~" ]] ; then
  echo "ERROR: File \"$GPGFILE.gpg~\" exists"
  echo "(This file temporarily saves \"$GPGFILE.gpg\". Maybe \"$GPGFILE.gpg\" can't be decrypted.)"
  usage
  exit 1
fi

if [[ -f "$GPGFILE" ]] ; then
  echo "ERROR: File \"$GPGFILE\" exists, but should not."
  echo "(It may be left over from some earlier error.)"
  echo "(Since \"$GPGFILE.gpg\" exists, you might use \"remove $GPGFILE\")"
  exit 1
fi

##############################################################################
## Set up editor
EDITOR=$HOME/bin/xtmedit
[[ ! -x $EDITOR ]] && EDITOR=$HOME/bin/editor
[[ ! -x $EDITOR ]] && EDITOR=$HOME/bin/xcbedit
[[ ! -x $EDITOR ]] && EDITOR=/usr/bin/nano
if [[ ! -x $EDITOR ]] ; then
  echo "No editor found"
  exit 1
fi

##############################################################################
## Decrypt
TEMP=`source make-temp`
gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>$TEMP
rc=$?
if [[ $rc != 0 ]] ; then
  rm -Rf $GPGFILE 2>/dev/null
  echo "gpg --output $GPGFILE --decrypt $GPGFILE.gpg"
  echo "ERROR: Decryption failure $rc."
  echo ""
  cat $TEMP
  echo ""
  echo "No file changed."
  rm $TEMP
  exit 1
fi
rm $TEMP

##############################################################################
## Edit, check resultant
$EDITOR $GPGFILE
if [[ ! -f "$GPGFILE" ]] ; then
  echo "File \"$GPGFILE\" deleted. No change will occur."
  exit 0
fi

##############################################################################
## Encrypt
rm -Rf $GPGFILE.gpg
gpg --encrypt $GPGFILE 2>$TEMP
rc=$?
if [[ $rc != 0 ]] ; then
  echo "gpg --encrypt $GPGFILE"
  echo "ERROR: Encryption failure $rc."
  echo ""
  cat $TEMP
  echo ""
  echo "File \"$GPGFILE\" still exists; \"$GPGFILE.gpg\" probably invalid."
  echo "Consider using \"intogpg $GPGFILE\" to retry encrypting."
  rm $TEMP
  exit 2
fi
rm $TEMP

remove $GPGFILE
exit 0
