#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       format
##
## Purpose-
##       Prevent accidental formatting of your hard disk.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       format A:
##       If you do not specify A: or B: as the first argument,
##       format does not work
##
##############################################################################

##############################################################################
## Parameter validation
if [[ -z "$1" ]] ; then
  echo "If you do not specify A: or B: as the first argument,"
  echo "format does not work."
  exit
fi

if [[ "a:" != "$1" && "b:" != "$1" && "A:" != "$1" && "B:" != "$1" ]] ; then
  echo "If you do not specify A: or B: as the first argument,"
  echo "format does not work."
  exit
fi

##############################################################################
## Process the format command
//c/windows/command/FORMAT.COM $*

