#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
## SPDX-License-Identifier: MIT
##----------------------------------------------------------------------------
##
## Title-
##       fromgpg
##
## Purpose-
##       Decrypt a GPG encrypted file.
##
## Last change date-
##       2025/08/14
##
## Usage-
##       fromgpg filename
##
## Implementation notes-
##       GPG configuration information is kept in ~/.gnupg/.
##       Using information in filename.gpg, GPG automatically selects the
##       decryption key.
##
##       "gpg --list-keys" displays your key ring.
##
## See also:
##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
##
##############################################################################

##############################################################################
## Function: USAGE
function usage
{
  echo ""
  echo "$0: Decrypt a file encrypted by GPG."
  echo "Usage: $0 filename"
  echo "File \"filename.gpg\" must exist, \"filename\" should not."
  echo "The GPG encrypted \"filename.gpg\" is decrypted into \"filename\","
  echo "then \"filename.gpg\" is then erased."

  echo ""
  echo "The information in \"filename.gpg\" allows GPG to automatically"
  echo "select the decryption key."
}

##############################################################################
## Parameter check
if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
  usage
  exit 1
fi

GPGFILE=$1
if [[ -z "$GPGFILE" ]] ; then
  echo "ERROR: Filename not specified"
  usage
  exit 1
fi

if [[ ! -z "$2" ]] ; then
  shift
  echo "ERROR: Extra parameters: $@"
  usage
  exit 1
fi

if [[ ! -f "$GPGFILE.gpg" ]] ; then
  echo "ERROR: File \"$GPGFILE.gpg\" does not exists"
  if [[ -f "$GPGFILE" ]] ; then
    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
  fi
  usage
  exit 1
fi

if [[ -f "$GPGFILE" ]] ; then
  echo "ERROR: File \"$GPGFILE\" exists, but should not."
  echo "(It may be left over from some earlier error.)"
  echo "(Since \"$GPGFILE.gpg\" exists, you can use \"remove $GPGFILE\")"
  exit 1
fi

##############################################################################
## Decrypt
TEMP=`source make-temp`
gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>$TEMP
rc=$?
if [[ $rc != 0 ]] ; then
  rm -Rf $GPGFILE 2>/dev/null
  echo "gpg --output $GPGFILE --decrypt $GPGFILE.gpg"
  echo "ERROR: Decryption failure $rc."
  echo ""
  cat $TEMP
  echo ""
  echo "No file changed."
  rm $TEMP
  exit 1
fi
rm $TEMP

##############################################################################
## Discard the original encrypted file
rm -Rf $GPGFILE.gpg

exit 0
