#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2018-2020 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       gitsynch
##
## Purpose-
##       Synch the trunk with another branch.
##
## Last change date-
##       2020/10/12
##
## Usage-
##       gitsynch branch
##
##############################################################################

##############################################################################
## Verify parameters
if [[ -z "$1" ]] ; then
    echo "Missing branch name, maint perhaps?"
    exit 1
elif [[ "$1" == "trunk" ]] ; then
    echo "Cannot synch trunk with trunk"
    exit 1
elif [[ ! -z "$2" ]] ; then
    echo "Extra parameter '$2', quitting"
    exit 1
fi

##############################################################################
## Synch a branch with the trunk, then resume that alternate branch
git checkout trunk
if [[ $? != 0 ]] ; then
    echo "Cannot checkout trunk, quitting"
    exit 1
fi

git merge $1
if [[ $? != 0 ]] ; then
    echo "Failed to merge branch $1. You are now in branch trunk"
    exit 1
fi

git checkout $1
if [[ $? != 0 ]] ; then
    echo "Failed to checkout branch $1. You are now in branch trunk"
    exit 1
fi

git gc
exit 0

