#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
## SPDX-License-Identifier: MIT
##----------------------------------------------------------------------------
##
## Title-
##       intogpg
##
## Purpose-
##       Encrypt a file using GPG encryption.
##
## Last change date-
##       2025/04/13
##
## Usage-
##       intogpg [-as user] filename
##
## Implementation notes-
##       GPG configuration information is kept in ~/.gnupg/.
##
##       There is no default encryption key.
##       - Use the default configuration file, ~/.gnupg/gpg.conf to define the
##         default encryption key.
##       - Use the "-as user" option to set or override the default
##         encryption key.
##       - If the "-as user" option isn't set and ~/.gnupg/gpg.conf doesn't
##         define a default encryption key, you will be prompted for a user
##         in your key ring to be used for encryption.
##       IF YOU ENCODE WITH AN ENCRYPTION KEY YOU CANNOT DECODE, YOUR DATA
##       WILL BE IRRETRIEVABLY LOST.
##
##       "gpg --list-keys" displays your key ring.
##
## See also:
##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
##
##############################################################################

##############################################################################
## Function: USAGE
function usage
{
  echo ""
  echo "$0: Use GPG to Encrypt a file."
  echo "Usage: $0 [-as user] filename"
  echo "File \"filename\" must exist, \"filename.gpg\" must not."
  echo "File \"filename\" is encrypted into \"filename.gpg\", then erased."

  echo ""
  echo "GPG configuration information is kept in ~/.gnupg/gpg.conf"
  echo "There is no default encryption key."
  echo "- Use the default configuration file, ~/.gnupg/gpg.conf to define the"
  echo "  default encryption key."
  echo "- Use the \"-as user\" option to set or override the default"
  echo "  encryption key."
  echo "- If the \"-as user\" option isn't set and ~/.gnupg/gpg.conf doesn't"
  echo "  define a default encryption key, you will be prompted for a user"
  echo "  in your key ring to be used for encryption."

  echo ""
  echo "  ** WARNING**"
  echo "    IF YOU CANNOT DECODE THE ENCRYPTION KEY, YOUR DATA WILL BE LOST."
  echo "    NOT ONLY LOST, IRRETRIEVABLY LOST; THE ORIGINAL FILE IS *DELETED*"
}

##############################################################################
## Parameter check
if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
  usage
  exit 1
fi

GPGFILE=$1
if [[ "$GPGFILE" = "-as" ]] ; then
  shift
  GPGUSER=$1
  if [[ -z "$GPGUSER" ]] ; then
    echo "ERROR: -as Required parameter 'username' not specified"
    usage
    exit 1
  fi

  shift
  GPGFILE=$1
fi

if [[ -z "$GPGFILE" ]] ; then
  echo "ERROR: Filename not specified"
  usage
  exit 1
fi

if [[ ! -z "$2" ]] ; then
  shift
  echo "ERROR: Extra parameters: $@"
  usage
  exit 1
fi

if [[ -f "$GPGFILE.gpg" ]] ; then
  echo "ERROR: File \"$GPGFILE.gpg\" already exists. Fix this problem."
  if [[ -f "$GPGFILE" ]] ; then
    echo "Note: File \"$GPGFILE\" also exists."
  else
    echo "Note: File \"$GPGFILE\" DOES NOT exist."
  fi
  usage
  exit 1
fi

if [[ ! -f "$GPGFILE" ]] ; then
  echo "ERROR: File \"$GPGFILE\" does not exist."
  usage
  exit 1
fi

[[ -n "$GPGUSER" ]] && GPGUSER="--recipient $GPGUSER"

##############################################################################
## Encrypt
gpg $GPGUSER --encrypt $GPGFILE
rc=$?
if [[ $rc != 0 ]] ; then
  rm $GPGFILE.gpg 2>/dev/null
  echo ""
  echo "gpg $GPGUSER --encrypt $GPGFILE"
  echo "ERROR: Encryption failure $rc."
  echo "File $GPGFILE unchanged. File $GPGFILE.gpg removed (if created.)"
  echo "(Do you have permission to write into this subdirectory?)"
  exit 2
fi

if [[ -n "$GPGUSER" ]] ; then
  echo "Parameter -as specified, File '$GPGFILE' kept."
else
  remove $GPGFILE
fi
exit 0
