#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       jrun
##
## Purpose-
##       Run a java class.
##
## Last change date-
##       2023/01/21
##
## Sample usage-
##       jrun Main parm1 parm2 parm3
##
##############################################################################

##############################################################################
## Verify environment
if [[ -z "$JAVA_HOME" ]] ; then
  echo "JAVA_HOME not initialized, cannot continue."
  exit 1
fi

##############################################################################
## Extract switches
##   4,000,000,000
sm="-Xms4000000000"
##      16,000,000
ss="  -Xss16000000"
sw=""
for i in $*
do
  case $i in
    -Xsm*)
      sm="$1"
      shift
      ;;

    -Xss*)
      ss="$1"
      shift
      ;;

    -*)
      sw="$sw $1"
      shift
      ;;

    *)
      break
      ;;
  esac
done

##############################################################################
## Verify environment
if [[ -z "$1" ]] ; then
  echo "Missing parameter, cannot continue."
  exit 1
fi

if [[ ! -f "$1.class" ]] ; then
  echo "Warning: $1.class does not exist."
fi

##############################################################################
## Run the command
set -x
java $sm $ss $sw -classpath "`cygpath --path --windows \"$CLASSPATH\"`" $*

