#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2015-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       machine
##
## Purpose-
##       Display machine information
##
## Last change date-
##       2019/10/08
##
## Usage-
##       machine
##
##############################################################################
MACHINE=`uname -m`
case $MACHINE in
  x86_64)
     echo "Intel 64 bit"
     ;;

  i686)
     echo "Intel 32 bit"
     ;;

  *)
     echo "*Unknown* $MACHINE"
     ;;
esac

