#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       mktar
##
## Purpose-
##       Create a gzipped tar file.
##
## Last change date-
##       2023/06/06
##
## Usage-
##       mktar {-v} pathname
##         (Creates pathname.tgz from subdirectory pathname)
##
##############################################################################

##############################################################################
## Extract switch names
sparm=""

for i in $*
do
  case $i in
    -f)
      echo "Specify the output filename as the first positional parameter"
      heading $0
      exit 1
      ;;

    -x)
      echo "Invalid switch $i"
      heading $0
      exit 1
      ;;

    -*)
      sparm="$sparm $i"
      shift
      ;;

    *)
      break
      ;;

  esac
done

##############################################################################
## Extract parameters
if [ "" = "$1" ] ; then
  echo "Missing path name"
  heading $0
  exit
fi
tar_name=$1
shift

if [ "" != "$1" ] ; then
  echo "Too many parameters"
  heading $0
  exit
fi

##############################################################################
## Verify parameters
if [ ! -d "$tar_name" ] ; then
  echo "'$tar_name' is not a directory."
  echo "Use a real directory name."
  exit
fi

if [ -e "$tar_name.tgz" ] ; then
  echo "'$tar_name.tgz' already exists."
  echo "Delete it and try again."
  exit
fi

##############################################################################
## Create the tgz file
cmd="tar $sparm -czf $tar_name.tgz $tar_name"
echo $cmd
$cmd
rc=$?
[[ $rc != 0 ]] && echo "tar command failed, exit code $rc"
exit $rc
