#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/license/mit)
##
## SPDX-License-Identifier: MIT
##----------------------------------------------------------------------------
##
## Title-
##       nettime
##
## Purpose-
##       Update clock using rdate.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       sudo nettime
##
##############################################################################
rdate -s -p time-a.nist.gov

