#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       nop
##
## Purpose-
##       Echo parameters. To do absolutely nothing, use true or false command.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       nop
##
##############################################################################

##############################################################################
## List the parameters one by one
for i in "$@"
do
  echo "'$i'"
done

[[ $- == *i* ]] && return 0         ## If interactively sourced
exit 0

