#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2015-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       osLINUX
##
## Purpose-
##       Test for LINUX operating system.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       if [[ ! -z "`osLINUX`" ]] ; then
##         echo LINUX code
##       fi
##
##############################################################################
echo `uname | grep Linux`

