#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2015-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       osWINDOWS
##
## Purpose-
##       Test for WINDOWS operating system.
##
## Last change date-
##       2019/10/08
##
## Usage-
##       (Used in make files)
##
##############################################################################
echo "" ## This is NOT Windows

