#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       outcol
##
## Purpose-
##       Display columns in file
##
## Last change date-
##       2019/10/08
##
## Usage-
##       outcol filename token-column ...
##
##############################################################################

##############################################################################
## Parameter validation
if [[ -z "$2" ]] ; then
  heading $0
  exit 1
fi

if [[ ! -f "$1" ]] ; then
  echo "Not a file: $1"
  heading $0
  exit 1
fi

##############################################################################
## Extract the file name
fileName=$1
shift

##############################################################################
## Extract the column list
colist=""
for i in $*
do
  if [[ -z "$colist" ]] ; then
    colist="\$${i}"
  else
    colist="${colist},\$${i}"
  fi
done

cat ${fileName} | gawk """{print ${colist}}"""

