#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2018-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/license/mit)
##
## SPDX-License-Identifier: MIT
##----------------------------------------------------------------------------
##
## Title-
##       remove
##
## Purpose-
##       Remove and shred a file.
##
## Last change date-
##       2025/08/14
##
## Usage-
##       remove [filename ...]
##
##############################################################################

##############################################################################
## Get options
OPTS=
for i in "$@"
do
  case $i in
    -*)
      OPTS="$OPTS $i"
      shift
      ;;

    *)
      break
      ;;
  esac
done

##############################################################################
## Use shred if available, otherwise use rm
REMOVE=rm
if [ -x /bin/shred ] ; then
  REMOVE="/bin/shred -u -z"
elif [ -x /usr/bin/shred ] ; then
  REMOVE="/usr/bin/shred -u -z"
else
  echo "Warning: shred not available, using rm"
  sleep 10
fi

##############################################################################
## Shred the files
rc=0
for i in "$@"
do
  if [[ -h $i ]] ; then
    echo "File '$i' is a link, try '$REMOVE' instead" 1>&2
    rc=1
  elif [[ -d $i ]] ; then
    echo "File: '$i' is a directory" 1>&2
    rc=1
  elif [[ ! -w $i ]] ; then
    echo "File: '$i' is not writable (or else it doesn't exist)" 1>&2
    rc=1
  else
    $REMOVE $OPTS $i
    [[ $rc != 0 ]] && rc=$?
  fi

  [[ $rc != 0 ]] && exit $rc
done

exit $rc
