#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2018-2020 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       rexleft
##
## Function-
##       rexterm left of bluebird terminal
##
## Last change date-
##       2020/04/10
##
## Usage-
##       rexleft {-x n} {-y n}
##
## Implementation note-
##       See: ~/bat/.tweaks --rexleft
##
##############################################################################

##############################################################################
# Handle -x, -y parameters
source .tweaks --rexleft
xgeo=$rexleft_xgeo
ygeo=$rexleft_ygeo

xsiz=${#xgeo[*]}
ysiz=${#ygeo[*]}

xndx=0
yndx=0

cs=""
skip=""
parm=""

for i in $*
do
  if [[ ! -z "$skip" ]] ; then
    skip=""
    shift
    continue
  fi

  case $i in
    -cs)
      shift
      cs="-cs $1"
      skip='Y'
      ;;

    -x | -X)
      shift
      v=$1
      xndx=0
      if [[ $v -ge $xsiz ]] ; then
        echo ERROR: $i -ge $xsiz, 0 assumed
      elif [[ $v -lt 0 ]] ; then
        echo ERROR: $i -lt 0, 0 assumed
      else
        xndx=$v
      fi
      skip='Y'
      ;;

    -y | -Y)
      shift
      v=$1
      yndx=0
      if [[ $v -ge $ysiz ]] ; then
        echo ERROR: $i -ge $ysiz, 0 assumed
      elif [[ $v -lt 0 ]] ; then
        echo ERROR: $i -lt 0, 0 assumed
      else
        yndx=$v
      fi
      skip='Y'
      ;;

    *)
      parm="$parm $i"
      shift
      ;;
  esac
done

xoff=${xgeo[$xndx]}
yoff=${ygeo[$yndx]}

##############################################################################
# Rexterm left of bluebird
rexterm $cs -geometry 80x24-$xoff+$yoff $parm

