#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       runDUMP
##
## Purpose-
##       Run a TCP trace
##
## Last change date-
##       2019/10/26
##
## Usage-
##       runDUMP
##
##############################################################################
sudo /usr/sbin/tcpdump -c 64 -e -v -s 128 -X multicast >dump.out

