#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2022 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       spell
##
## Purpose-
##       Spell checker.
##
## Last change date-
##       2022/02/10
##
## Usage-
##       spell word ...
##
##############################################################################
if [ -x /bin/hunspell ] ; then
  for i in "$@"
  do
    errors=`echo $i | hunspell -l -d en_US,local`
    if [[ -z "$errors" ]] ; then echo OK: $i
    else echo "NG: $errors"
    fi
  done
else
  for i in "$@"
  do
    errors=`echo $i | aspell list`
    if [[ -z "$errors" ]] ; then echo OK: $i
    else echo "NG: $errors"
    fi
  done
fi
