#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       spell
##
## Purpose-
##       Spell checker.
##
## Last change date-
##       2019/10/26
##
## Usage-
##       spell file
##
##############################################################################
errors=`echo $* | aspell list`
if [[ -z "$errors" ]] ; then echo OK
else echo Misspelled: $errors
fi

