#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       sshftp
##
## Purpose-
##       sftp name reminder.
##
## Last change date-
##       2019/10/26
##
## Usage-
##       sshftp remote-system
##
##############################################################################
sftp $*

