#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2021 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       tidy
##
## Purpose-
##       Wrapper for clang-tidy
##
## Last change date-
##       2021/01/25
##
##############################################################################

##############################################################################
## Set options
export OPTS="-D_CC_GCC -D_OS_BSD -D_HW_X86 -D_OS_LINUX -IS -IH"
export OPTS="$OPTS -finline-functions -std=gnu++17 -Wall -Wextra -Werror"
export OPTS="$OPTS -Wmissing-declarations -Wswitch-default"
## export OPTS="$OPTS --checks="-header-filter=.*,-system-headers"

##############################################################################
## Run clang-tidy
set -x
clang-tidy -header-filter=.* -system-headers "$@" -- $OPTS

