#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2025 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       viewgpg
##
## Purpose-
##       View a GPG encrypted file.
##
## Last change date-
##       2024/04/13
##
## Usage-
##       viewgpg [-as user] filename
##
## Implementation notes-
##       GPG configuration information is kept in ~/.gnupg/.
##       Using information in filename.gpg, GPG automatically selects the
##       decryption key.
##
##       "gpg --list-keys" displays your key ring.
##
## See also:
##       GPG user's guide:  https://www.gnupg.org/documentation/guides.html
##       GPG user's manual: https://www.gnupg.org/documentation/manuals.html
##
##############################################################################

##############################################################################
## Function: USAGE
function usage
{
  echo ""
  echo "$0: View a file encrypted by GPG."
  echo "Usage: $0 filename"
  echo "File \"filename.gpg\" must exist; \"filename\" should not."
  echo "The GPG encrypted \"filename.gpg\" is decrypted into \"filename\","
  echo "then edited."
  echo "Once the editor exits, the decrypted \"filename\" is deleted."

  echo ""
  echo "The information in \"filename.gpg\" allows GPG to automatically"
  echo "select the decryption key."

  echo ""
  echo "The encrypted file, \"filename.gpg\", is never modified."
}

##############################################################################
## Parameter check
if [[ "$1" = "-help" || "$1" = "--help" ]] ; then
  usage
  exit 1
fi

GPGFILE=$1
if [[ -z "$GPGFILE" ]] ; then
  echo "ERROR: Filename not specified"
  usage
  exit 1
fi

if [[ ! -z "$2" ]] ; then
  shift
  echo "ERROR: Extra parameters: $@"
  usage
  exit 1
fi

if [[ ! -f "$GPGFILE.gpg" ]] ; then
  echo "ERROR: File \"$GPGFILE.gpg\" does not exist"
  if [[ -f "$GPGFILE" ]] ; then
    echo "(Since \"$GPGFILE\" exists, consider using \"intogpg $GPGFILE\")"
  fi
  usage
  exit 1
fi

if [[ -f "$GPGFILE" ]] ; then
  echo "ERROR: File \"$GPGFILE\" exists, but should not."
  echo "(It may be left over from some earlier error.)"
  echo "(Since \"$GPGFILE.gpg\" exists, you can use \"remove $GPGFILE\")"
  exit 1
fi

##############################################################################
## Set up editor
EDITOR=$HOME/bin/editor
[[ ! -x $EDITOR ]] && EDITOR=$HOME/bin/xtmedit
[[ ! -x $EDITOR ]] && EDITOR=/usr/bin/nano
if [[ ! -x $EDITOR ]] ; then
  echo "No editor found"
  exit 1
fi

##############################################################################
## Decrypt
gpg --output $GPGFILE --decrypt $GPGFILE.gpg 2>/dev/null
rc=$?
if [[ $rc != 0 ]] ; then
  rm $GPGFILE 2>/dev/null
  echo "ERROR: Decryption failure $rc."
  echo "No file changed."
  exit 1
fi

##############################################################################
## Edit; discard decrypted file
$EDITOR $GPGFILE
remove $GPGFILE 2>/dev/null

exit 0
