#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2021 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       viewgpg
##
## Purpose-
##       View a GPG encrypted file.
##
## Last change date-
##       2021/06/10
##
## Usage-
##       viewgpg [-as userid] filename
##
##############################################################################

##############################################################################
## Function: USAGE
function usage
{
  echo ""
  echo "$0: View a GPG encrypted file"
  echo "Usage: $0 file"
  echo "Filename file.gpg must exist"
  echo "The GPG encrypted file is decrypted into \"file\", and this"
  echo "unencrypted file is edited. The unencrypted file is deleted"
  echo "when the editor exits."
}

##############################################################################
## Parameter check
GPGFILE=$1
if [ -z "$GPGFILE" ] ; then
  echo "Error: filename not specified"
  usage
  exit 1
fi

if [ ! -z "$2" ] ; then
  echo "Error: Extra parameter(s)"
  usage
  exit 1
fi

if [ ! -f "$GPGFILE.gpg" ] ; then
  echo "Error: file \"$GPGFILE.gpg\" does not exist"
  usage
  exit 1
fi

if [ -f "$GPGFILE" ] ; then
  echo "Error: file \"$GPGFILE\" exists, but should not."
  echo "(It may be left over from an earlier error.)"
  exit 1
fi

##############################################################################
## Decrypt
gpg --output $GPGFILE --decrypt $GPGFILE.gpg
rc=$?
if [ $rc != 0 ] ; then
  echo "Error: Decryption failure."
  echo "No file changed."
  exit 1
fi

##############################################################################
## Edit, remove temporary file
. setupEDIT                         ## (If no display, use ncurses editor)
$EDITOR $GPGFILE
remove $GPGFILE 2>/dev/null

exit 0
