#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       viewer
##
## Purpose-
##       File viewer, displays specified files.
##
## Last change date-
##       2019/10/26
##
## Usage-
##       viewer
##
##############################################################################

##############################################################################
## Run nautilus
if [ -x /usr/bin/nautilus ] ; then
  [ -n "$1" ] && echo "Parameters are ignored!"
  /usr/bin/nautilus file://"$PWD" 2>/dev/null
  exit $?
fi

if [ -x /bin/nautilus ] ; then
  [ -n "$1" ] && echo "Parameters are ignored!"
  /bin/nautilus file://"$PWD" 2>/dev/null
  exit $?
fi

[ -z "$1" ] && echo "No file specified!"

##############################################################################
## Run gimp
if [ -x /usr/bin/gimp ] ; then
  /usr/bin/gimp "$@" 2>/dev/null
  exit $?
fi

if [ -x /bin/gimp ] ; then
  /bin/gimp "$@" 2>/dev/null
  exit $?
fi

##############################################################################
## Run display
if [ -x /usr/bin/display ] ; then
  /usr/bin/display "$@"
  exit $?
fi

if [ -x /bin/display ] ; then
  /bin/display "$@"
  exit $?
fi

##############################################################################
## No viewer available
echo "No viewer available"
exit 1

