#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2017-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       WebServer
##
## Purpose-
##       Start the web server
##
## Last change date-
##       2019/10/26
##
## Usage-
##       WebServer
##
##############################################################################
. setupJAVA
cd ~/web
make start

