#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       whence
##
## Purpose-
##       Return path of executable.
##
## Last change date-
##       2019/10/26
##
## Usage-
##       whence execName
##
##############################################################################
tempname=/tmp/temp.$$
echo `type $1 2>/dev/null` >$tempname
read name is path junk <$tempname
rm $tempname
if [[ "$name" = "$1" && "$is" = "is" ]] ; then
  echo $path
fi

