#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2022 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       regression
##
## Function-
##       Regression tests
##
## Last change date-
##       2022/04/25
##
## Implementation notes-
##       Run this script from ~/src/cpp/obj/pub/Test, the test subdirectory.
##
##############################################################################

##############################################################################
## Environment
DDIR=S/script/regression.d

##############################################################################
## Parameter analysis
make=1
parm=
setx=0
for arg in "$@"
do
  case $arg in
    --nomake)
      make=0
      shift
      ;;

    --*)
      parm="$arg $parm"
      shift
      ;;

    -x)
      setx=1
      shift
      ;;

    -*)
      echo "Parameter '$arg' ignored"
      shift
      ;;

    *)
      break
      ;;
  esac
done

test_set="$@"
if [ "$1" == "" ] ; then
  test_set=`ls $DDIR`
fi

##############################################################################
## Make sure the test library is up to date
if [[ $make != 0 ]] ; then
  echo "Building tests..."
  make all
  rc=$?
  if [[ $rc != 0 ]] ; then
    echo "Test build failed"
    exit $rc
  fi
  echo ""
fi

##############################################################################
## Run the regression tests
[ $setx != 0 ] && set -x
for test in $test_set
do
  [[ ! -a "$DDIR/$test" ]] && { echo "FAIL: '$DDIR/$test' missing"; exit 1; }
  if [[ -x "$DDIR/$test" && ! -d "$DDIR/$test" ]] ; then
    $DDIR/$test $parm
    rc=$?
    if [[ $rc == 0 ]] ; then
      echo "PASS: $test"
    else
      echo "FAIL: $test, rc $rc"
      exit $rc
    fi
  fi
done

echo "PASS: ** ALL TESTS **"
