##############################################################################
##
##       Copyright (c) 2023-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       DEV library controls and dependencies.
##
## Last change date-
##       2024/09/30
##
## Implementation notes-
##       Include this file from CYGWIN/LINUX Makefiles that use DEV library.
##
##############################################################################
ifeq "" "$(_LIBPUB_DEV_MAKEFILE_BSD_INCLUDED)"
_LIBPUB_DEV_MAKEFILE_BSD_INCLUDED := "TRUE"

###################################### Dependent libraries
ifeq "" "$(USE_SHARED)"
LLIBS  += -L$(LIBDIR) -ldev ########## DEV library
$(MAKEXE): $(LIBDIR)/libdev.a
endif

include $(INCDIR)/pub/Makefile.BSD ### PUB library
endif
