#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2018-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       CA_sign
##
## Function-
##       Sign a certificate.
##
## Last change date-
##       2019/04/03
##
## Usage-
##       CA_sign certificate-filename
##
##############################################################################

##############################################################################
## Verify the request
[[ -z "$1" ]] && { echo "Missing parameter"; exit 1; }
[[ -n "$2" ]] && { echo "Extra parameter(s)"; exit 1; }
[[ -f "./signed.pem" ]]  && { echo "./signed.pem already exists"; exit 1; }

[[ ! -f "$1" ]] && { echo "$1 is not a file"; exit 1; }

[[ -z "$OPENSSL_CONF" ]] && { echo "OPENSSL_CONF is not set"; exit 1; }
[[ ! -f "$OPENSSL_CONF" ]] && { echo "\$OPENSSL_CONF is not a file"; exit 1; }

[[ "${OPENSSL_CONF: -12}" != "/openssl.cnf" ]] && { echo "\$OPENSSL_CONF not */openssl.cnf"; exit 1; }
OPENSSL_PATH=${OPENSSL_CONF:0:-12}

echo OPENSSL_PATH $OPENSSL_PATH
echo OPENSSL_CONF $OPENSSL_CONF

##############################################################################
## Sign the certificate
openssl ca -in $1
rc=$?
[[ $rc != 0 ]] && exit $rc

##############################################################################
## Return the signed certificate
read serial <$OPENSSL_PATH/serial.old
cat $OPENSSL_PATH/newcerts/$serial.pem $OPENSSL_PATH/cacert.pem >signed.pem

