##############################################################################
##
##       Copyright (c) 2018 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.WIN
##
## Purpose-
##       WINDOWS Makefile customization.
##
## Last change date-
##       2018/01/01
##
## Implementation notes-
##       ** NOT TESTED. Build is currently BSD only. **
##
##############################################################################

##############################################################################
## Local options
COPTS  += /I. ##################### Include libbrary

##############################################################################
## Local library list (Currently unused.)
LIBOBJ := ######################### CURRENTLY UNUSED
## LIBOBJ += Command.o
## MAKEXE := $(patsubst $(OBJDIR)/Command,,$(MAKEXE))
##
## LLIBS  += -L. -llocal

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: make.dir
make.dir: $(MAKEXE)

.PHONY: make.all
make.all: $(MAKEXE)

all: make.all

##############################################################################
## TARGET: liblocal.a
liblocal.a: $(LIBOBJ)
	$(AR) $@ $^
	touch $@

## NOT CURRENTLY USED
## $(MAKEXE): liblocal.a

################################### Add pub controls and dependencies
include $(INCDIR)/pub/Makefile.WIN

##############################################################################
## Run the default program
.PHONY: do
do: make.dir
	@Enviro

##############################################################################
## Makefile cleanup
clean : clean.dir
.PHONY: clean.dir
clean.dir: ;
	-@rm -f liblocal.a >/dev/null 2>/dev/null
