##############################################################################
##
##       Copyright (c) 2018-2022 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization.
##
## Last change date-
##       2022/04/21
##
##############################################################################

##############################################################################
## Local module list

##############################################################################
## Local library
LIBOBJ := ############################
LIBOBJ += Empty.o
MAKEXE := $(patsubst $(OBJDIR)/Empty,,$(MAKEXE))

LLIBS  += -L. -llocal

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: default
default: $(DEFAULT)

.PHONY: make.dir
make.dir: Enviro

.PHONY: make.all
make.all: $(MAKEXE)

all: make.all

################################### Add pub controls and dependencies
include $(INCDIR)/pub/Makefile.BSD
include $(INCDIR)/com/Makefile.BSD

##############################################################################
## TARGET: liblocal.a
liblocal.a: $(LIBOBJ)
	$(AR) $@ $^
	touch $@

$(MAKEXE): liblocal.a

##############################################################################
## Run the Dirty program
.PHONY: dirty
dirty: Dirty
	@Dirty

##############################################################################
## Run the default program
.PHONY: do
do: TestDisp
	TestDisp --hcdm --verbose
## do: make.dir
## 	@Enviro

##############################################################################
## Makefile cleanup
.PHONY: clean.dir
clean: clean.dir
clean.dir: ;
	-@rm liblocal.a      >/dev/null 2>/dev/null
	-@rm trace.mem       >/dev/null 2>/dev/null
	-@rm test_bug.*      >/dev/null 2>/dev/null
