##############################################################################
##
##       Copyright (c) 2018-2021 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization.
##
## Last change date-
##       2021/09/06
##
##############################################################################

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: default
default: $(DEFAULT)

.PHONY: make.dir
make.dir: Enviro

.PHONY: make.all
make.all: $(MAKEXE)

all: make.all

################################### Add pub controls and dependencies
include $(INCDIR)/pub/Makefile.BSD

##############################################################################
## Run the Dirty program
.PHONY: dirt
dirt: Dirty
	@Dirty

##############################################################################
## Run the default program
.PHONY: do
do: make.dir
	@Enviro
