##############################################################################
##
##       Copyright (c) 2018-2024 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       ~/src/cpp/lib/pub/Test/Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile customization.
##
## Last change date-
##       2024/03/01
##
##############################################################################

##############################################################################
## Local module list

##############################################################################
## Local library
LIBOBJ := ############################
LIBOBJ += Empty.o
MAKEXE := $(patsubst $(OBJDIR)/Empty,,$(MAKEXE))

## Attempting static link
ignore += -flinker-output=exec
ignore += -static
LLIBS  += -L. -llocal

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: default
default: configure $(DEFAULT)

.PHONY: make.dir
make.dir: $(MAKEXE)
## make.dir: Enviro

.PHONY: make.all
make.all: $(MAKEXE)

all: make.all

##############################################################################
## TARGET: liblocal.a
liblocal.a: $(LIBOBJ)
	$(AR) $@ $^
	touch $@

##############################################################################
## TARGET: configure
.PHONY: configure
configure: ;
	@../../../../../bat/sys/configure.sh src/cpp/lib/pub

##############################################################################
## Run the Dirty program
.PHONY: dirty
dirty: Dirty
	@Dirty

##############################################################################
## Run the default program
.PHONY: do
do: TestDisp
	TestDisp --timing

##############################################################################
## Run the Quick program
.PHONY: quick
quick: Quick
	@Quick --all --verbose

##############################################################################
## Make a certificate
host:=$(shell "hostname")
cert.dir: ;
	@printf "US\nState\nLocality\nCompany\nDivision\n$(host)\n\n\n" | \
openssl req -x509 -nodes -days 3653 -newkey rsa:2048 -keyout private.pem -out public.pem >/dev/null 2>/dev/null
	@printf "Generated private.pem, public.pem, valid for 10 years.\n"
	@touch cert.dir

.PHONY: cert keys
cert: cert.dir
keys: cert.dir                      ## Alias for cert

##############################################################################
## Verify the certificates
.PHONY: verify
verify: cert.dir
	openssl rsa -in private.pem -check -noout
	openssl x509 -in public.pem -text -noout

##############################################################################
## Dependency controls
include $(INCDIR)/pub/Makefile.BSD  ## PUB library controls
include $(INCDIR)/com/Makefile.BSD  ## Test_num.cpp requires Random

$(MAKEXE): $(LIBDIR)/libpub.a       ## All execs depend on PUB library
$(MAKEXE): liblocal.a               ## All execs depend on local library
TestSock: cert.dir                  ## TestSock depends on certificates

##############################################################################
## Makefile cleanup
.PHONY: clean.dir pristine.dir
pristine: pristine.dir
pristine.dir: ;
	@rm -f .have-version
	@rm -f cert.dir
	@rm -f private.pem
	@rm -f public.pem

clean: clean.dir
clean.dir: ;
	@rm -f liblocal.a
	@rm -f test_bug.*
	@rm -f trace.mem
