#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2016-2020 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       curltimer
##
## Purpose-
##       Test httpserver speed.
##
## Last change date-
##       2020/04/10
##
## Usage-
##       httpserver {{loop-count} site}
##
##############################################################################
count=25
if [[ ! -z "$1" ]] ; then
    count=$1
fi

site="http://localhost:7777/"
if [[ ! -z "$2" ]] ; then
    site=$2
fi

start=`Time.py`
n=0
while [ $n -lt $count ]
do
    curl $site >/dev/null 2>/dev/null
    n=$((n+1))
done

finis=`Time.py`
secs=`Math.py $finis - $start`
Format.py "%s operations in %.6f seconds" $count $secs
rate=`Math.py $count / $secs`

Format.py "%.2f operations/second" $rate

