##############################################################################
##
##       Copyright (c) 2022 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile versioning
##
## Last change date-
##       2022/10/23
##
##############################################################################

##############################################################################
## Local library/executable lists
LIBOBJ := $(MAKOBJ) ################## Default, all files are library files
LIBOBJ := $(patsubst $(OBJDIR)/Dirty.o,,$(LIBOBJ)) ## (Not distributed)
LIBOBJ := $(patsubst $(OBJDIR)/Thing.o,,$(LIBOBJ)) ## (Not distributed)
LIBOBJ := $(patsubst $(OBJDIR)/Include.o,,$(LIBOBJ)) ## (Built on demand)

MAKEXE := ############################
MAKEXE += T_Option
MAKEXE += T_Quick
MAKEXE += T_Stream
MAKEXE += TestIoda
LIBOBJ := $(patsubst $(OBJDIR)/T_Option.o,,$(LIBOBJ))
LIBOBJ := $(patsubst $(OBJDIR)/T_Quick.o,,$(LIBOBJ))
LIBOBJ := $(patsubst $(OBJDIR)/T_Stream.o,,$(LIBOBJ))
LIBOBJ := $(patsubst $(OBJDIR)/TestIoda.o,,$(LIBOBJ))

LLIBS  += -L. -llocal
CLIBS  += -lrt

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: default
default: $(MAKEXE)

all: default

##############################################################################
## TARGET: liblocal.a
liblocal.a: $(LIBOBJ)
	$(AR) $@ $^
	touch $@

##############################################################################
## Targets: do, include, list, quick
.PHONY: do
do: T_Stream
	T_Stream

.PHONY: include                     ## Include is only compiled on demand
include: Include
	Include

.PHONY: list
list: ;
	@echo "Targets: do, include, list"
	@echo "Removes: client, dirty, option, server, stress, test"

.PHONY: quick
quick: T_Quick
	T_Quick --all --verbose

## TEMPORARY: TODO: REMOVE ###################################################
.PHONY: client dirty option server stress test
client: T_Stream
	T_Stream --server --client

option: T_Option
	T_Option

server: T_Stream
	T_Stream --server

stress: T_Stream
	T_Stream --server --stress --verbose

test: T_Option T_Stream
	T_Option
	@echo ""
	T_Stream --server --client
	@echo ""
	T_Stream --server --stress --time 10

.PHONY: ioda
ioda: TestIoda
	TestIoda

## Dirty contains a set of quick and dirty tests, and is not distributed.
Dirty: Dirty.o Thing.o liblocal.a
	$(LD) -o Dirty Dirty.o Thing.o $(CLOAD) $(CLIBS)

dirty: Dirty
	Dirty

##############################################################################
## Make a certificate
host:=$(shell "hostname")
ifneq "" "$(USE_LOCALHOST)"
  host:="localhost"
endif

cert.dir: ;
	@printf "US\nState\nLocality\nCompany\nDivision\n$(host)\n\n\n" | \
openssl req -x509 -nodes -days 3653 -newkey rsa:2048 -keyout private.pem -out public.pem >/dev/null 2>/dev/null
	@printf "Generated private.pem, public.pem, valid for 10 years.\n"
	@touch cert.dir

.PHONY: cert keys
cert: cert.dir
keys: cert.dir                      ## Alias for cert

##############################################################################
## Verify the certificates
.PHONY: verify
verify: ;
	openssl rsa -in private.pem -check -noout
	openssl x509 -in public.pem -text -noout

##############################################################################
## Dependency controls
include $(INCDIR)/pub/Makefile.BSD  ## PUB library controls

$(MAKEXE): liblocal.a cert.dir      ## Execs depend on local library, certs

Include: $(INCDIR)/pub/http/*       ## Include test depends on include

##############################################################################
## Makefile cleanup
.PHONY: clean.dir pristine.dir
pristine : pristine.dir
pristine.dir: ;
	-@rm -f cert.dir    >/dev/null 2>/dev/null
	-@rm -f private.pem >/dev/null 2>/dev/null
	-@rm -f public.pem  >/dev/null 2>/dev/null
	-@rm -f log/*       >/dev/null 2>/dev/null
	-@rm -f trace.mem   >/dev/null 2>/dev/null

clean : clean.dir
clean.dir: ;
	-@rm -f Dirty       >/dev/null 2>/dev/null
	-@rm -f Include     >/dev/null 2>/dev/null
	-@rm -f liblocal.a  >/dev/null 2>/dev/null

