##############################################################################
##
##       Copyright (c) 2022-2023 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##############################################################################
##
## Title-
##       Makefile.BSD
##
## Purpose-
##       CYGWIN/LINUX Makefile versioning
##
## Last change date-
##       2023/06/04
##
##############################################################################

##############################################################################
## Required libraries
CLIBS  += -lrt

##############################################################################
## Executables only built on demand
MAKEXE := $(patsubst $(OBJDIR)/Dirty,,$(MAKEXE))   ## Not distributed
MAKEXE := $(patsubst $(OBJDIR)/Include,,$(MAKEXE)) ## For include file test
MAKEXE := $(patsubst $(OBJDIR)/Thing,,$(MAKEXE))   ## Not distributed

##############################################################################
## Set default target
ifeq "" "$(DEFAULT)"
DEFAULT:= make.dir
endif

.PHONY: default
default: $(DEFAULT)

all: default

make.dir: $(MAKEXE) cert.dir        ## Default: build executable, certificates
	touch make.dir

##############################################################################
## Targets: do, include, list, quick
.PHONY: do
do: T_Stream
	T_Stream --server --stress=1 --major=2

.PHONY: include                     ## Include is only compiled on demand
include: Include
	Include

.PHONY: list
list: ;
	@echo "Targets: do, include, list"
	@echo "Removes: client, dirty, option, server, stress, test"

.PHONY: quick
quick: T_Quick
	T_Quick --all --verbose

##############################################################################
## Dirty contains a set of quick and dirty tests, and is not distributed.
Dirty: Dirty.o Thing.o
	$(LD) -o Dirty Dirty.o Thing.o $(CLOAD) $(CLIBS)

dirty: Dirty
	Dirty

##############################################################################
## Make a certificate
host:=$(shell "hostname")
ifneq "" "$(USE_LOCALHOST)"
  host:="localhost"
endif

cert.dir: ;
	@printf "US\nState\nLocality\nCompany\nDivision\n$(host)\n\n\n" | \
openssl req -x509 -nodes -days 3653 -newkey rsa:2048 -keyout private.pem -out public.pem >/dev/null 2>/dev/null
	@printf "Generated private.pem, public.pem, valid for 10 years.\n"
	@touch cert.dir

.PHONY: cert keys
cert: cert.dir
keys: cert.dir                      ## Alias for cert

##############################################################################
## Verify the certificates
.PHONY: verify
verify: ;
	openssl rsa -in private.pem -check -noout
	openssl x509 -in public.pem -text -noout

##############################################################################
## Dependency controls
include $(INCDIR)/dev/Makefile.BSD  ## DEV library controls
include $(INCDIR)/pub/Makefile.BSD  ## PUB library controls

Include: $(INCDIR)/pub/http/*       ## Include test depends on include

$(MAKEXE): $(LIBDIR)/libdev.a $(LIBDIR)/libpub.a

##############################################################################
## Makefile cleanup
.PHONY: clean.dir pristine.dir
pristine : pristine.dir
pristine.dir: ;
	-@rm -f cert.dir    >/dev/null 2>/dev/null
	-@rm -f private.pem >/dev/null 2>/dev/null
	-@rm -f public.pem  >/dev/null 2>/dev/null
	-@rm -f log/*       >/dev/null 2>/dev/null
	-@rm -f trace.mem   >/dev/null 2>/dev/null
	-@rm -f *.out       >/dev/null 2>/dev/null

clean : clean.dir
clean.dir: ;
	-@rm -f make.dir    >/dev/null 2>/dev/null
	-@rm -f Dirty       >/dev/null 2>/dev/null
	-@rm -f Include     >/dev/null 2>/dev/null

