#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (C) 2010-2019 Frank Eskesen.
##
##       This file is free content, distributed under the MIT license.
##       (See accompanying file LICENSE.MIT or the original contained
##       within https://opensource.org/licenses/MIT)
##
##----------------------------------------------------------------------------
##
## Title-
##       ungnome
##
## Purpose-
##       Stop the gnome terminal session
##
## Last change date-
##       2019/10/26
##
## Usage-
##       ungnome
##
##############################################################################
killer gnome-session
killer gnome-screen
killer gnome-panel
killer dbus
killer esd
killer nautilus
killer pam-panel
killer libexec

