#!/bin/bash
##----------------------------------------------------------------------------
##
##       Copyright (c) 2006-2021 Frank Eskesen.
##
##       This file is free content, distributed under the "un-license,"
##       explicitly released into the Public Domain.
##       (See accompanying file LICENSE.UNLICENSE or the original
##       contained within http://unlicense.org)
##
##----------------------------------------------------------------------------
##
## Title-
##       make
##
## Function-
##       Local alias for make
##
## Last change date-
##       2021/07/09
##
## Usage-
##       ./make
##
## Notes-
##       fileformat=unix
##
##############################################################################

##############################################################################
# Build the file
g++ -o makeproj -O3 -D_OS_BSD -I~/src/cpp/inc -Wall -Wextra Makeproj.cpp

##############################################################################
# Test the result
rc=$?
if [[ $rc != 0 ]] ; then
  echo "Compile failed code $rc"
  exit $rc
fi

##############################################################################
# Handle install option
if [[ "$1" == "install" ]] ; then
  [[ -d ~/bin ]] || { echo "creating ~/bin"; mkdir ~/bin; }
  strip makeproj
  mv -i makeproj ~/bin/.
  exit 0
fi

##############################################################################
# Handle pristine option
if [[ "$1" == "pristine" ]] ; then
  rm -f makeproj
  exit 0
fi

