#!/bin/bash

set -x
encodeuu encodeuu.exe >encode.uu
decodeuu out          <encode.uu
diff out encodeuu.exe
if [[ $? != 0 ]] ; then
  echo "en/decodeuu failure"
  exit 1
fi

encodeuu test1        >test1.uu
decodeuu out          <test1.uu
diff out test1
if [[ $? != 0 ]] ; then
  echo "en/decodeuu failure"
  exit 1
fi

encodeuu test2        >test2.uu
decodeuu out          <test2.uu
diff out test2
if [[ $? != 0 ]] ; then
  echo "en/decodeuu failure"
  exit 1
fi

encodeuu test3        >test3.uu
decodeuu out          <test3.uu
diff out test3
if [[ $? != 0 ]] ; then
  echo "en/decodeuu failure"
  exit 1
fi

rm out *.uu
echo "NO errors"

